### ISSUE TITLE
Implement task list workflow in MIQA 

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#89]
- [ ] Tasks are assigned to individuals via supervisor
- [ ] Reviewers login and check what tasks have been assigned to them via task list panel
- [ ] Reviewers can check what tasks have been completed in the task list by her

**Comment by aashish24** [comment]
Summary of discussion:
- Use Django admin panel for task assignments 
- Supervisor is the admin for now (we discussed four roles: admin, supervisor, reviewer, technician)
- Use different colors for task that needs to be reviewed and the ones that are completed
-

**Comment by venkatabhishek** [comment]
Discussion Summary:
- A **task** is composed of multiple **experiments** (one to many relationship) and is assigned to a single user
- Move locking logic from sessions to experiments (this will require removing session locking UI). That is, at most one user will have write access to a single given experiment
- Task List tab will allow supervisor to create tasks, associate experiments with task, and assign task to user

**Comment by curtislisle** [comment]
There could be a benefit to keeping the Session/Project level locking UI and feature if it doesn’t conflict with experiment level locking.  For example, an archived project could be completely locked, or a new project locked by the administrator initially until they decide to release it.  Project level locking would supercede experiment locking.   It is OK to remove this if it makes things complicated.  I haven’t looked at the current locking UI yet, but I could imaging a multicolumn layout with the projects in the first column (and a lock or unlock icon), then depending on which project is selected, the experiments will appear and can be locked or unlocked.  

Just throwing this idea out for consideration.  Thanks for a good meeting today. 

Curt

**Comment by aashish24** [comment]
Another consideration for keeping the session lock is (if possible and avoids conflict as @curtislisle mentioned) to keep the feature same as we discussed with Stanford (until we have further clarifications from them)

**Comment by venkatabhishek** [comment]
I agree it would be nice to keep the session locks, but I foresee that it might cause conflict/require much more complicated logic.

A simpler solution to allow for sessions to be archived/locked might be to just include a boolean field on the session itself. If this is set to true (i.e. locked), none of its experiments can be locked or assigned as tasks to reviewers. This is different then the previous implementation because there is no notion of who owns the lock and thus no need to user checking. Does this still solve that use case?

**Comment by curtislisle** [comment]
Yes, this still solves the use case and avoids locking logic issues.  Good solution!

**Comment by curtislisle** [comment]
I found this system and forgot to mention it earlier, but this system seems to use Django in the back end to manage tickets with free text questions and answers.  Reviewing this system may only be a waste of time, but I figured it couldn't hurt to mention, just in case there are any good ideas in here:  https://github.com/TicketVise/ticketvise

**Comment by aashish24** [comment]
Related to #175 #71
